
import { Doctor, ForumTopic, Article, Hospital } from './types';

export const DOCTORS: Doctor[] = [
  { id: 1, name: 'Dr. Amina Rahman', specialty: 'Cardiologist', location: 'City General Hospital', rating: 4.7, availability: 'Available Today', avatarColor: 'bg-blue-100 text-blue-800' },
  { id: 2, name: 'Dr. Laila Chowdhury', specialty: 'Dermatologist', location: 'St. Mary\'s Medical Center', rating: 4.9, availability: 'Next: Mon 10 AM', avatarColor: 'bg-pink-100 text-pink-800' },
  { id: 3, name: 'Dr. Ken Thompson', specialty: 'Pediatrician', location: 'Lakeside Children\'s Hospital', rating: 4.8, availability: 'Available Today', avatarColor: 'bg-green-100 text-green-800' },
  { id: 4, name: 'Dr. Sarah Chen', specialty: 'Orthopedist', location: 'Metro Health Institute', rating: 4.6, availability: 'Next: Tue 2 PM', avatarColor: 'bg-purple-100 text-purple-800' },
  { id: 5, name: 'Dr. Michael Williams', specialty: 'Neurologist', location: 'University Medical Group', rating: 4.9, availability: 'Available Today', avatarColor: 'bg-yellow-100 text-yellow-800' },
  { id: 6, name: 'Dr. Jessica Martinez', specialty: 'Oncologist', location: 'Pine Creek Specialty Care', rating: 4.8, availability: 'Next: Wed 11 AM', avatarColor: 'bg-indigo-100 text-indigo-800' },
  { id: 7, name: 'Dr. David Jones', specialty: 'Gastroenterologist', location: 'City General Hospital', rating: 4.7, availability: 'Available Today', avatarColor: 'bg-red-100 text-red-800' },
  { id: 8, name: 'Dr. Linda Davis', specialty: 'Urologist', location: 'Northside Regional', rating: 4.5, availability: 'Next: Thu 3 PM', avatarColor: 'bg-gray-100 text-gray-800' },
  { id: 9, name: 'Dr. Robert Garcia', specialty: 'ENT Specialist', location: 'Southpoint General', rating: 4.8, availability: 'Available Today', avatarColor: 'bg-blue-100 text-blue-800' },
  { id: 10, name: 'Dr. Jennifer Miller', specialty: 'Psychiatrist', location: 'Community Clinic', rating: 4.9, availability: 'Next: Fri 9 AM', avatarColor: 'bg-pink-100 text-pink-800' },
  { id: 11, name: 'Dr. William Brown', specialty: 'Endocrinologist', location: 'Oak Valley Hospital', rating: 4.6, availability: 'Available Today', avatarColor: 'bg-green-100 text-green-800' },
  { id: 12, name: 'Dr. Elizabeth Wilson', specialty: 'Pulmonologist', location: 'St. Mary\'s Medical Center', rating: 4.7, availability: 'Next: Mon 1 PM', avatarColor: 'bg-purple-100 text-purple-800' },
  { id: 13, name: 'Dr. James Anderson', specialty: 'Rheumatologist', location: 'Metro Health Institute', rating: 4.8, availability: 'Available Today', avatarColor: 'bg-yellow-100 text-yellow-800' },
  { id: 14, name: 'Dr. Patricia Thomas', specialty: 'General Practitioner', location: 'Community Clinic', rating: 4.9, availability: 'Next: Tue 10 AM', avatarColor: 'bg-indigo-100 text-indigo-800' },
  { id: 15, name: 'Dr. John Taylor', specialty: 'Cardiologist', location: 'University Medical Group', rating: 4.5, availability: 'Available Today', avatarColor: 'bg-red-100 text-red-800' },
  { id: 16, name: 'Dr. Barbara Moore', specialty: 'Dermatologist', location: 'Pine Creek Specialty Care', rating: 4.8, availability: 'Next: Wed 2 PM', avatarColor: 'bg-gray-100 text-gray-800' },
  { id: 17, name: 'Dr. Richard Jackson', specialty: 'Pediatrician', location: 'Lakeside Children\'s Hospital', rating: 4.9, availability: 'Available Today', avatarColor: 'bg-blue-100 text-blue-800' },
  { id: 18, name: 'Dr. Susan Martin', specialty: 'Orthopedist', location: 'City General Hospital', rating: 4.6, availability: 'Next: Thu 4 PM', avatarColor: 'bg-pink-100 text-pink-800' },
  { id: 19, name: 'Dr. Joseph Lee', specialty: 'Neurologist', location: 'Northside Regional', rating: 4.7, availability: 'Available Today', avatarColor: 'bg-green-100 text-green-800' },
  { id: 20, name: 'Dr. Sarah Perez', specialty: 'Oncologist', location: 'Southpoint General', rating: 4.8, availability: 'Next: Fri 11 AM', avatarColor: 'bg-purple-100 text-purple-800' },
  { id: 21, name: 'Dr. Charles Thompson', specialty: 'Gastroenterologist', location: 'Oak Valley Hospital', rating: 4.9, availability: 'Available Today', avatarColor: 'bg-yellow-100 text-yellow-800' },
  { id: 22, name: 'Dr. Karen White', specialty: 'Urologist', location: 'St. Mary\'s Medical Center', rating: 4.5, availability: 'Next: Mon 9 AM', avatarColor: 'bg-indigo-100 text-indigo-800' },
  { id: 23, name: 'Dr. Christopher Harris', specialty: 'ENT Specialist', location: 'Metro Health Institute', rating: 4.8, availability: 'Available Today', avatarColor: 'bg-red-100 text-red-800' },
  { id: 24, name: 'Dr. Nancy Sanchez', specialty: 'Psychiatrist', location: 'Community Clinic', rating: 4.7, availability: 'Next: Tue 1 PM', avatarColor: 'bg-gray-100 text-gray-800' },
  { id: 25, name: 'Dr. Daniel Clark', specialty: 'Endocrinologist', location: 'University Medical Group', rating: 4.6, availability: 'Available Today', avatarColor: 'bg-blue-100 text-blue-800' },
  { id: 26, name: 'Dr. Lisa Ramirez', specialty: 'Pulmonologist', location: 'Pine Creek Specialty Care', rating: 4.9, availability: 'Next: Wed 3 PM', avatarColor: 'bg-pink-100 text-pink-800' },
  { id: 27, name: 'Dr. Matthew Lewis', specialty: 'Rheumatologist', location: 'City General Hospital', rating: 4.8, availability: 'Available Today', avatarColor: 'bg-green-100 text-green-800' },
  { id: 28, name: 'Dr. Betty Robinson', specialty: 'General Practitioner', location: 'Northside Regional', rating: 4.7, availability: 'Next: Thu 10 AM', avatarColor: 'bg-purple-100 text-purple-800' },
  { id: 29, name: 'Dr. Anthony Walker', specialty: 'Cardiologist', location: 'Southpoint General', rating: 4.6, availability: 'Available Today', avatarColor: 'bg-yellow-100 text-yellow-800' },
  { id: 30, name: 'Dr. Margaret Young', specialty: 'Dermatologist', location: 'Oak Valley Hospital', rating: 4.8, availability: 'Next: Fri 2 PM', avatarColor: 'bg-indigo-100 text-indigo-800' },
  { id: 31, name: 'Dr. Mark Allen', specialty: 'Pediatrician', location: 'Lakeside Children\'s Hospital', rating: 4.9, availability: 'Available Today', avatarColor: 'bg-red-100 text-red-800' },
  { id: 32, name: 'Dr. Sandra King', specialty: 'Orthopedist', location: 'St. Mary\'s Medical Center', rating: 4.7, availability: 'Next: Mon 11 AM', avatarColor: 'bg-gray-100 text-gray-800' },
  { id: 33, name: 'Dr. Paul Wright', specialty: 'Neurologist', location: 'Metro Health Institute', rating: 4.8, availability: 'Available Today', avatarColor: 'bg-blue-100 text-blue-800' },
  { id: 34, name: 'Dr. Emily Scott', specialty: 'Oncologist', location: 'Community Clinic', rating: 4.9, availability: 'Next: Tue 4 PM', avatarColor: 'bg-pink-100 text-pink-800' },
  { id: 35, name: 'Dr. Andrew Torres', specialty: 'Gastroenterologist', location: 'University Medical Group', rating: 4.6, availability: 'Available Today', avatarColor: 'bg-green-100 text-green-800' },
  { id: 36, name: 'Dr. Donna Nguyen', specialty: 'Urologist', location: 'Pine Creek Specialty Care', rating: 4.5, availability: 'Next: Wed 9 AM', avatarColor: 'bg-purple-100 text-purple-800' },
  { id: 37, name: 'Dr. Joshua Hill', specialty: 'ENT Specialist', location: 'City General Hospital', rating: 4.8, availability: 'Available Today', avatarColor: 'bg-yellow-100 text-yellow-800' },
  { id: 38, name: 'Dr. Michelle Flores', specialty: 'Psychiatrist', location: 'Northside Regional', rating: 4.7, availability: 'Next: Thu 1 PM', avatarColor: 'bg-indigo-100 text-indigo-800' },
  { id: 39, name: 'Dr. Kevin Green', specialty: 'Endocrinologist', location: 'Southpoint General', rating: 4.9, availability: 'Available Today', avatarColor: 'bg-red-100 text-red-800' },
  { id: 40, name: 'Dr. Dorothy Adams', specialty: 'Pulmonologist', location: 'Oak Valley Hospital', rating: 4.8, availability: 'Next: Fri 10 AM', avatarColor: 'bg-gray-100 text-gray-800' },
  { id: 41, name: 'Dr. Brian Nelson', specialty: 'Rheumatologist', location: 'St. Mary\'s Medical Center', rating: 4.6, availability: 'Available Today', avatarColor: 'bg-blue-100 text-blue-800' },
  { id: 42, name: 'Dr. Carol Baker', specialty: 'General Practitioner', location: 'Metro Health Institute', rating: 4.7, availability: 'Next: Mon 2 PM', avatarColor: 'bg-pink-100 text-pink-800' },
  { id: 43, name: 'Dr. George Hall', specialty: 'Cardiologist', location: 'Community Clinic', rating: 4.8, availability: 'Available Today', avatarColor: 'bg-green-100 text-green-800' },
  { id: 44, name: 'Dr. Amanda Rivera', specialty: 'Dermatologist', location: 'University Medical Group', rating: 4.9, availability: 'Next: Tue 11 AM', avatarColor: 'bg-purple-100 text-purple-800' },
  { id: 45, name: 'Dr. Edward Campbell', specialty: 'Pediatrician', location: 'Lakeside Children\'s Hospital', rating: 4.7, availability: 'Available Today', avatarColor: 'bg-yellow-100 text-yellow-800' },
  { id: 46, name: 'Dr. Melissa Mitchell', specialty: 'Orthopedist', location: 'Pine Creek Specialty Care', rating: 4.8, availability: 'Next: Wed 4 PM', avatarColor: 'bg-indigo-100 text-indigo-800' },
  { id: 47, name: 'Dr. Ronald Carter', specialty: 'Neurologist', location: 'City General Hospital', rating: 4.9, availability: 'Available Today', avatarColor: 'bg-red-100 text-red-800' },
  { id: 48, name: 'Dr. Deborah Roberts', specialty: 'Oncologist', location: 'Northside Regional', rating: 4.6, availability: 'Next: Thu 9 AM', avatarColor: 'bg-gray-100 text-gray-800' },
  { id: 49, name: 'Dr. Timothy Gomez', specialty: 'Gastroenterologist', location: 'Southpoint General', rating: 4.7, availability: 'Available Today', avatarColor: 'bg-blue-100 text-blue-800' },
  { id: 50, name: 'Dr. Stephanie Phillips', specialty: 'Urologist', location: 'Oak Valley Hospital', rating: 4.8, availability: 'Next: Fri 1 PM', avatarColor: 'bg-pink-100 text-pink-800' },
  { id: 51, name: 'Dr. Jason Evans', specialty: 'ENT Specialist', location: 'St. Mary\'s Medical Center', rating: 4.9, availability: 'Available Today', avatarColor: 'bg-green-100 text-green-800' },
  { id: 52, name: 'Dr. Rebecca Turner', specialty: 'Psychiatrist', location: 'Metro Health Institute', rating: 4.7, availability: 'Next: Mon 10 AM', avatarColor: 'bg-purple-100 text-purple-800' },
  { id: 53, name: 'Dr. Jeffrey Diaz', specialty: 'Endocrinologist', location: 'Community Clinic', rating: 4.8, availability: 'Available Today', avatarColor: 'bg-yellow-100 text-yellow-800' },
  { id: 54, name: 'Dr. Laura Parker', specialty: 'Pulmonologist', location: 'University Medical Group', rating: 4.9, availability: 'Next: Tue 2 PM', avatarColor: 'bg-indigo-100 text-indigo-800' },
  { id: 55, name: 'Dr. Ryan Cruz', specialty: 'Rheumatologist', location: 'Pine Creek Specialty Care', rating: 4.6, availability: 'Available Today', avatarColor: 'bg-red-100 text-red-800' },
  { id: 56, name: 'Dr. Sharon Edwards', specialty: 'General Practitioner', location: 'City General Hospital', rating: 4.8, availability: 'Next: Wed 11 AM', avatarColor: 'bg-gray-100 text-gray-800' },
  { id: 57, name: 'Dr. Jacob Collins', specialty: 'Cardiologist', location: 'Northside Regional', rating: 4.9, availability: 'Available Today', avatarColor: 'bg-blue-100 text-blue-800' },
  { id: 58, name: 'Dr. Cynthia Reyes', specialty: 'Dermatologist', location: 'Southpoint General', rating: 4.7, availability: 'Next: Thu 3 PM', avatarColor: 'bg-pink-100 text-pink-800' },
  { id: 59, name: 'Dr. Gary Stewart', specialty: 'Pediatrician', location: 'Lakeside Children\'s Hospital', rating: 4.8, availability: 'Available Today', avatarColor: 'bg-green-100 text-green-800' },
  { id: 60, name: 'Dr. Kathleen Morris', specialty: 'Orthopedist', location: 'Oak Valley Hospital', rating: 4.9, availability: 'Next: Fri 9 AM', avatarColor: 'bg-purple-100 text-purple-800' },
  { id: 61, name: 'Dr. Nicholas Morales', specialty: 'Neurologist', location: 'St. Mary\'s Medical Center', rating: 4.6, availability: 'Available Today', avatarColor: 'bg-yellow-100 text-yellow-800' },
  { id: 62, name: 'Dr. Amy Murphy', specialty: 'Oncologist', location: 'Metro Health Institute', rating: 4.8, availability: 'Next: Mon 1 PM', avatarColor: 'bg-indigo-100 text-indigo-800' },
  { id: 63, name: 'Dr. Eric Cook', specialty: 'Gastroenterologist', location: 'Community Clinic', rating: 4.9, availability: 'Available Today', avatarColor: 'bg-red-100 text-red-800' },
  { id: 64, name: 'Dr. Shirley Rogers', specialty: 'Urologist', location: 'University Medical Group', rating: 4.7, availability: 'Next: Tue 10 AM', avatarColor: 'bg-gray-100 text-gray-800' },
  { id: 65, name: 'Dr. Jonathan Gutierrez', specialty: 'ENT Specialist', location: 'Pine Creek Specialty Care', rating: 4.8, availability: 'Available Today', avatarColor: 'bg-blue-100 text-blue-800' },
  { id: 66, name: 'Dr. Angela Ortiz', specialty: 'Psychiatrist', location: 'City General Hospital', rating: 4.9, availability: 'Next: Wed 2 PM', avatarColor: 'bg-pink-100 text-pink-800' },
  { id: 67, name: 'Dr. Stephen Morgan', specialty: 'Endocrinologist', location: 'Northside Regional', rating: 4.6, availability: 'Available Today', avatarColor: 'bg-green-100 text-green-800' },
  { id: 68, name: 'Dr. Helen Cooper', specialty: 'Pulmonologist', location: 'Southpoint General', rating: 4.8, availability: 'Next: Thu 4 PM', avatarColor: 'bg-purple-100 text-purple-800' },
  { id: 69, name: 'Dr. Larry Peterson', specialty: 'Rheumatologist', location: 'Oak Valley Hospital', rating: 4.9, availability: 'Available Today', avatarColor: 'bg-yellow-100 text-yellow-800' },
  { id: 70, name: 'Dr. Anna Bailey', specialty: 'General Practitioner', location: 'St. Mary\'s Medical Center', rating: 4.7, availability: 'Next: Fri 11 AM', avatarColor: 'bg-indigo-100 text-indigo-800' },
  { id: 71, name: 'Dr. Justin Reed', specialty: 'Cardiologist', location: 'Metro Health Institute', rating: 4.8, availability: 'Available Today', avatarColor: 'bg-red-100 text-red-800' },
  { id: 72, name: 'Dr. Brenda Kelly', specialty: 'Dermatologist', location: 'Community Clinic', rating: 4.9, availability: 'Next: Mon 9 AM', avatarColor: 'bg-gray-100 text-gray-800' },
  { id: 73, name: 'Dr. Scott Howard', specialty: 'Pediatrician', location: 'Lakeside Children\'s Hospital', rating: 4.6, availability: 'Available Today', avatarColor: 'bg-blue-100 text-blue-800' },
  { id: 74, name: 'Dr. Pamela Ramos', specialty: 'Orthopedist', location: 'University Medical Group', rating: 4.8, availability: 'Next: Tue 1 PM', avatarColor: 'bg-pink-100 text-pink-800' },
  { id: 75, name: 'Dr. Brandon Kim', specialty: 'Neurologist', location: 'Pine Creek Specialty Care', rating: 4.9, availability: 'Available Today', avatarColor: 'bg-green-100 text-green-800' },
  { id: 76, name: 'Dr. Nicole Cox', specialty: 'Oncologist', location: 'City General Hospital', rating: 4.7, availability: 'Next: Wed 3 PM', avatarColor: 'bg-purple-100 text-purple-800' },
  { id: 77, name: 'Dr. Benjamin Ward', specialty: 'Gastroenterologist', location: 'Northside Regional', rating: 4.8, availability: 'Available Today', avatarColor: 'bg-yellow-100 text-yellow-800' },
  { id: 78, name: 'Dr. Emma Richardson', specialty: 'Urologist', location: 'Southpoint General', rating: 4.9, availability: 'Next: Thu 10 AM', avatarColor: 'bg-indigo-100 text-indigo-800' },
  { id: 79, name: 'Dr. Samuel Watson', specialty: 'ENT Specialist', location: 'Oak Valley Hospital', rating: 4.6, availability: 'Available Today', avatarColor: 'bg-red-100 text-red-800' },
  { id: 80, name: 'Dr. Samantha Brooks', specialty: 'Psychiatrist', location: 'St. Mary\'s Medical Center', rating: 4.8, availability: 'Next: Fri 2 PM', avatarColor: 'bg-gray-100 text-gray-800' },
  { id: 81, name: 'Dr. Gregory Chavez', specialty: 'Endocrinologist', location: 'Metro Health Institute', rating: 4.9, availability: 'Available Today', avatarColor: 'bg-blue-100 text-blue-800' },
  { id: 82, name: 'Dr. Katherine Wood', specialty: 'Pulmonologist', location: 'Community Clinic', rating: 4.7, availability: 'Next: Mon 11 AM', avatarColor: 'bg-pink-100 text-pink-800' },
  { id: 83, name: 'Dr. Frank James', specialty: 'Rheumatologist', location: 'University Medical Group', rating: 4.8, availability: 'Available Today', avatarColor: 'bg-green-100 text-green-800' },
  { id: 84, name: 'Dr. Christine Bennet', specialty: 'General Practitioner', location: 'Pine Creek Specialty Care', rating: 4.9, availability: 'Next: Tue 4 PM', avatarColor: 'bg-purple-100 text-purple-800' },
  { id: 85, name: 'Dr. Alexander Gray', specialty: 'Cardiologist', location: 'City General Hospital', rating: 4.6, availability: 'Available Today', avatarColor: 'bg-yellow-100 text-yellow-800' },
  { id: 86, name: 'Dr. Debra Mendoza', specialty: 'Dermatologist', location: 'Northside Regional', rating: 4.8, availability: 'Next: Wed 9 AM', avatarColor: 'bg-indigo-100 text-indigo-800' },
  { id: 87, name: 'Dr. Raymond Ruiz', specialty: 'Pediatrician', location: 'Lakeside Children\'s Hospital', rating: 4.9, availability: 'Available Today', avatarColor: 'bg-red-100 text-red-800' },
  { id: 88, name: 'Dr. Rachel Hughes', specialty: 'Orthopedist', location: 'Southpoint General', rating: 4.7, availability: 'Next: Thu 1 PM', avatarColor: 'bg-gray-100 text-gray-800' },
  { id: 89, name: 'Dr. Patrick Price', specialty: 'Neurologist', location: 'Oak Valley Hospital', rating: 4.8, availability: 'Available Today', avatarColor: 'bg-blue-100 text-blue-800' },
  { id: 90, name: 'Dr. Catherine Alvarez', specialty: 'Oncologist', location: 'St. Mary\'s Medical Center', rating: 4.9, availability: 'Next: Fri 10 AM', avatarColor: 'bg-pink-100 text-pink-800' },
  { id: 91, name: 'Dr. Jack Castillo', specialty: 'Gastroenterologist', location: 'Metro Health Institute', rating: 4.6, availability: 'Available Today', avatarColor: 'bg-green-100 text-green-800' },
  { id: 92, name: 'Dr. Janet Sanders', specialty: 'Urologist', location: 'Community Clinic', rating: 4.8, availability: 'Next: Mon 2 PM', avatarColor: 'bg-purple-100 text-purple-800' },
  { id: 93, name: 'Dr. Dennis Patel', specialty: 'ENT Specialist', location: 'University Medical Group', rating: 4.9, availability: 'Available Today', avatarColor: 'bg-yellow-100 text-yellow-800' },
  { id: 94, name: 'Dr. Ruth Myers', specialty: 'Psychiatrist', location: 'Pine Creek Specialty Care', rating: 4.7, availability: 'Next: Tue 11 AM', avatarColor: 'bg-indigo-100 text-indigo-800' },
  { id: 95, name: 'Dr. Jerry Long', specialty: 'Endocrinologist', location: 'City General Hospital', rating: 4.8, availability: 'Available Today', avatarColor: 'bg-red-100 text-red-800' },
  { id: 96, name: 'Dr. Maria Ross', specialty: 'Pulmonologist', location: 'Northside Regional', rating: 4.9, availability: 'Next: Wed 4 PM', avatarColor: 'bg-gray-100 text-gray-800' },
  { id: 97, name: 'Dr. Tyler Foster', specialty: 'Rheumatologist', location: 'Southpoint General', rating: 4.6, availability: 'Available Today', avatarColor: 'bg-blue-100 text-blue-800' },
  { id: 98, name: 'Dr. Diane Jimenez', specialty: 'General Practitioner', location: 'Oak Valley Hospital', rating: 4.8, availability: 'Next: Thu 9 AM', avatarColor: 'bg-pink-100 text-pink-800' },
  { id: 99, name: 'Dr. Aaron Bell', specialty: 'Cardiologist', location: 'St. Mary\'s Medical Center', rating: 4.9, availability: 'Available Today', avatarColor: 'bg-green-100 text-green-800' },
  { id: 100, name: 'Dr. Virginia Powell', specialty: 'Dermatologist', location: 'Metro Health Institute', rating: 4.7, availability: 'Next: Fri 1 PM', avatarColor: 'bg-purple-100 text-purple-800' },
];

export const FORUM_TOPICS: ForumTopic[] = [
  {
    id: 1,
    title: 'Managing anxiety and stress in a busy work life',
    author: 'Sarah J.',
    time: '2 hours ago',
    category: 'Mental Health',
    replies: 15,
    lastActivity: 'by Mark P. • 5 minutes ago'
  },
  {
    id: 2,
    title: 'Tips for starting a healthy, sustainable diet?',
    author: 'Alex C.',
    time: '1 day ago',
    category: 'Nutrition',
    replies: 8,
    lastActivity: 'by Emily R. • 45 minutes ago'
  },
  {
    id: 3,
    title: 'Good exercises for relieving chronic back pain',
    author: 'John D.',
    time: '3 days ago',
    category: 'Fitness',
    replies: 22,
    lastActivity: 'by Dr. Lisa (Verified) • 1 hour ago'
  }
];

export const ARTICLES: Article[] = [
  {
    id: 1,
    title: 'The Importance of a Balanced Diet for a Healthy Life',
    category: 'Nutrition',
    excerpt: 'Discover how a balanced diet with the right nutrients can boost your immune system, improve your energy levels, and help prevent chronic diseases...',
    image: 'https://picsum.photos/seed/nutrition/400/300'
  },
  {
    id: 2,
    title: '5 Simple Mindfulness Exercises for a Calmer Day',
    category: 'Mental Health',
    excerpt: 'In our busy lives, taking a moment to pause is crucial. Learn five simple mindfulness exercises you can do anywhere to reduce stress and increase focus...',
    image: 'https://picsum.photos/seed/mentalhealth/400/300'
  },
  {
    id: 3,
    title: 'How to Start a Fitness Routine You\'ll Actually Stick With',
    category: 'Fitness',
    excerpt: 'Starting a new fitness routine can be challenging. We provide practical tips on setting realistic goals and finding activities you enjoy to build a lasting habit...',
    image: 'https://picsum.photos/seed/fitness/400/300'
  }
];

export const NEARBY_HOSPITALS: Hospital[] = [
  { id: 1, name: 'City General Hospital', type: 'General', distance: '1.2 km' },
  { id: 2, name: 'St. Mary\'s Medical Center', type: 'Specialty', distance: '3.5 km' },
  { id: 3, name: 'Community Clinic', type: 'Clinic', distance: '0.8 km' },
  { id: 4, name: 'Metro Health Institute', type: 'Specialty', distance: '4.1 km' },
  { id: 5, name: 'Oak Valley Hospital', type: 'General', distance: '5.6 km' },
  { id: 6, name: 'Pine Creek Specialty Care', type: 'Clinic', distance: '2.3 km' },
  { id: 7, name: 'Lakeside Children\'s Hospital', type: 'Children\'s Hospital', distance: '7.8 km' },
  { id: 8, name: 'University Medical Group', type: 'General', distance: '6.2 km' },
  { id: 9, name: 'Northside Regional', type: 'General', distance: '10.5 km' },
  { id: 10, name: 'Southpoint General', type: 'General', distance: '1.9 km' },
];

const sortedDoctors = [...DOCTORS].sort((a, b) => b.rating - a.rating);
export const TOP_RATED_DOCTORS: Pick<Doctor, 'id' | 'name' | 'rating'>[] = 
  sortedDoctors.slice(0, 20).map(({id, name, rating}) => ({id, name, rating}));
